# L4: Optimize DSPy Agent with DSPy Optimizer

<p style="background-color:#fff6e4; padding:15px; border-width:3px; border-color:#f5ecda; border-style:solid; border-radius:6px"> ⏳ <b>Note <code>(Kernel Starting)</code>:</b> This notebook takes about 30 seconds to be ready to use. You may start and watch the video while you wait.</p>

In [1]:
from helper import get_openai_api_key
openai_api_key = get_openai_api_key()

import os

os.environ["OPENAI_API_KEY"] = get_openai_api_key()

<div style="background-color:#fff6ff; padding:13px; border-width:3px; border-color:#efe6ef; border-style:solid; border-radius:6px">
<p> 💻 &nbsp; <b>Access <code>requirements.txt</code> and <code>helper.py</code> files:</b> 1) click on the <em>"File"</em> option on the top menu of the notebook and then 2) click on <em>"Open"</em>.</p>

<p> ⬇ &nbsp; <b>Download Notebooks:</b> 1) click on the <em>"File"</em> option on the top menu of the notebook and then 2) click on <em>"Download as"</em> and select <em>"Notebook (.ipynb)"</em>.</p>

<p> 📒 &nbsp; For more help, please see the <em>"Appendix – Tips, Help, and Download"</em> Lesson.</p>
</div>

In [2]:
import mlflow

In [3]:
from helper import get_mlflow_tracking_uri

mlflow_tracking_uri = get_mlflow_tracking_uri()
mlflow.set_tracking_uri(mlflow_tracking_uri)

In [4]:
mlflow.set_experiment("dspy_course_4")

2025/06/11 12:41:54 INFO mlflow.tracking.fluent: Experiment with name 'dspy_course_4' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/272351694886347245', creation_time=1749645714448, experiment_id='272351694886347245', last_update_time=1749645714448, lifecycle_stage='active', name='dspy_course_4', tags={}>

In [5]:
mlflow.dspy.autolog(log_evals=True, log_compiles=True, log_traces_from_compile=True)

In [6]:
import dspy

dspy.configure(lm=dspy.LM("openai/gpt-4o-mini"))

## Build a RAG Agent

In [7]:
def search_wikipedia(query: str) -> list[str]:
    results = dspy.ColBERTv2(url="http://20.102.90.50:2017/wiki17_abstracts")(query, k=3)
    return [x["text"] for x in results]

react = dspy.ReAct("question -> answer", tools=[search_wikipedia])

In [8]:
import json

# Load trainset
trainset = []
with open("trainset.jsonl", "r") as f:
    for line in f:
        trainset.append(dspy.Example(**json.loads(line)).with_inputs("question"))

# Load valset
valset = []
with open("valset.jsonl", "r") as f:
    for line in f:
        valset.append(dspy.Example(**json.loads(line)).with_inputs("question"))

In [9]:
# Overview of the dataset.
print(trainset[0])

Example({'question': 'Are Smyrnium and Nymania both types of plant?', 'answer': 'yes'}) (input_keys={'question'})

In [10]:
tp = dspy.MIPROv2(
    metric=dspy.evaluate.answer_exact_match,
    auto="light",
    num_threads=16
)

In [11]:
dspy.cache.load_memory_cache("./memory_cache.pkl")

In [12]:
optimized_react = tp.compile(
    react,
    trainset=trainset,
    valset=valset,
    requires_permission_to_run=False,
)

2025/06/11 12:42:40 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '57871a627850406aa53dfee4bf7d523a', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current dspy workflow
2025/06/11 12:42:40 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 20
minibatch: True
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 100

2025/06/11 12:42:40 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2025/06/11 12:42:40 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2025/06/11 12:42:40 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 18%|█▊        | 18/100 [00:03<00:13,  5.97it/s]

Bootstrapped 4 full traces after 18 examples for up to 1 rounds, amounting to 18 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 4/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

  1%|          | 1/100 [00:00<00:12,  7.97it/s]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 5/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 10%|█         | 10/100 [00:01<00:10,  8.19it/s]

Bootstrapped 4 full traces after 10 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 6/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

  2%|▏         | 2/100 [00:00<00:12,  7.88it/s]

Bootstrapped 1 full traces after 2 examples for up to 1 rounds, amounting to 2 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/06/11 12:42:47 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2025/06/11 12:42:47 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2025/06/11 12:42:48 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}} in JSON format.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all infomration for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {} in JSON format.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given the fields `question` and `trajectory`, your task is to produce the field `answer`. You are functioning as an intelligent agent that will analyze the `question` and use the `trajectory` of previous thoughts and actions to determine the next steps needed to gather information. You will interleave the following actions in each turn:

1. Formulate a `next_thought` that reflects your reasoning about the current situation and outlines your plan for gathering the necessary information.
2. Select a `next_tool_name` from the available tools, which can either be `search_wikipedia` or `finish`.
3. Provide `next_tool_args` that contain the appropriate arguments for the chosen tool.

When you choose `search_wikipedia`, ensure that the `query` is relevant to the `question` at hand. If you determine that you have gathered sufficient information to answer the `question`, select `finish` to mark the task as complete.

Remember to maintain a clear and structured approach throughout the process, as this will enhance your ability to retrieve accurate and relevant information effectively.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: 2: You are a knowledgeable trivia agent. Given the fields `question`, produce the fields `answer`. In each episode, you will receive the `question` as input along with a `trajectory` that tracks your previous thoughts and tool calls. Your goal is to utilize the supplied tools to gather necessary information for producing the `answer`.

Interleave your reasoning in `next_thought`, select the appropriate `next_tool_name` (either `search_wikipedia` to gather more information or `finish` to complete the task), and provide the necessary `next_tool_args`. After each tool call, append the resulting observation to your trajectory.

Reason about the current situation and plan your next steps as you work through the task. The tools available to you are:
(1) `search_wikipedia`, which takes arguments {'query': {'type': 'string'}} in JSON format.
(2) `finish`, which signals that all information for producing the outputs, i.e. `answer`, is now available.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given a factual question, utilize the `Predict` module to analyze the provided `trajectory` of previous interactions. Your task is to synthesize the information gathered from external sources, particularly Wikipedia, and articulate a step-by-step reasoning process that leads to a well-founded and coherent final answer. Ensure that your response addresses the question directly, incorporating relevant details from the observations made during the information retrieval process.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the fields `question` and `trajectory`, reason through the information gathered to produce a coherent `answer` based on the accumulated knowledge and interactions. Ensure that the final output reflects the logical steps taken to arrive at the conclusion.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2025/06/11 12:42:50 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 25 - Full Evaluation of Default Program ==

Average Metric: 31.00 / 100 (31.0%): 100%|██████████| 100/100 [00:04<00:00, 22.57it/s]

2025/06/11 12:42:55 INFO dspy.evaluate.evaluate: Average Metric: 31 / 100 (31.0%)

🏃 View run eval_full_0 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/f17e2bed0d9d4d098895075bb22f790e
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:42:55 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 31.0

/usr/local/lib/python3.11/site-packages/optuna/_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2025/06/11 12:42:55 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 2 / 25 - Minibatch ==

Average Metric: 3.00 / 35 (8.6%): 100%|██████████| 35/35 [00:02<00:00, 17.05it/s]

2025/06/11 12:42:57 INFO dspy.evaluate.evaluate: Average Metric: 3 / 35 (8.6%)

🏃 View run eval_minibatch_0 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/2ac7999aa7ff48c487c2efbf9c14b99b
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:42:57 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 8.57 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/06/11 12:42:57 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57]
2025/06/11 12:42:57 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0]
2025/06/11 12:42:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 31.0
2025/06/11 12:42:57 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:42:57 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 3 / 25 - Minibatch ==

Average Metric: 18.00 / 35 (51.4%): 100%|██████████| 35/35 [00:01<00:00, 17.57it/s]

2025/06/11 12:42:59 INFO dspy.evaluate.evaluate: Average Metric: 18 / 35 (51.4%)

🏃 View run eval_minibatch_1 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/b75068f90ce44a76889db752ceed56d7
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:42:59 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 51.43 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/06/11 12:42:59 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43]
2025/06/11 12:42:59 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0]
2025/06/11 12:42:59 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 31.0
2025/06/11 12:42:59 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:42:59 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 4 / 25 - Minibatch ==

Average Metric: 5.00 / 35 (14.3%): 100%|██████████| 35/35 [00:01<00:00, 18.38it/s]

2025/06/11 12:43:01 INFO dspy.evaluate.evaluate: Average Metric: 5 / 35 (14.3%)

🏃 View run eval_minibatch_2 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/a2fab0a9db8141afa0cb465a8e3ba20b
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:43:01 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 14.29 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/06/11 12:43:01 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29]
2025/06/11 12:43:01 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0]
2025/06/11 12:43:01 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 31.0
2025/06/11 12:43:01 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:43:01 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 5 / 25 - Minibatch ==

Average Metric: 19.00 / 35 (54.3%): 100%|██████████| 35/35 [00:01<00:00, 19.17it/s]

2025/06/11 12:43:03 INFO dspy.evaluate.evaluate: Average Metric: 19 / 35 (54.3%)

🏃 View run eval_minibatch_3 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/0f8df749457a47e4a10d6f8e3c6c56b5
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:43:04 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 54.29 on minibatch of size 35 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/06/11 12:43:04 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29]
2025/06/11 12:43:04 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0]
2025/06/11 12:43:04 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 31.0
2025/06/11 12:43:04 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:43:04 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 6 / 25 - Minibatch ==

Average Metric: 17.00 / 35 (48.6%): 100%|██████████| 35/35 [00:06<00:00,  5.08it/s]

2025/06/11 12:43:11 INFO dspy.evaluate.evaluate: Average Metric: 17 / 35 (48.6%)
2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.57 on minibatch of size 35 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57]
2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0]
2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 31.0
2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 25 - Full Evaluation =====
2025/06/11 12:43:11 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 54.29) from minibatch trials...

🏃 View run eval_minibatch_4 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/0979903d6bac49bb864c44d5fc269866
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 50.00 / 100 (50.0%): 100%|██████████| 100/100 [00:25<00:00,  3.87it/s]

2025/06/11 12:43:37 INFO dspy.evaluate.evaluate: Average Metric: 50 / 100 (50.0%)
2025/06/11 12:43:37 INFO dspy.teleprompt.mipro_optimizer_v2: New best full eval score! Score: 50.0
2025/06/11 12:43:37 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0]
2025/06/11 12:43:37 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:43:37 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2025/06/11 12:43:37 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/06/11 12:43:37 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 8 / 25 - Minibatch ==

🏃 View run eval_full_1 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/0ba21a3493be493da57b61c5b934e1a7
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 15.00 / 35 (42.9%): 100%|██████████| 35/35 [00:06<00:00,  5.52it/s]

2025/06/11 12:43:43 INFO dspy.evaluate.evaluate: Average Metric: 15 / 35 (42.9%)

🏃 View run eval_minibatch_5 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/d55487ce6cb445f98a4fc51574851423
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:43:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 42.86 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/06/11 12:43:43 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86]
2025/06/11 12:43:43 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0]
2025/06/11 12:43:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:43:43 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:43:43 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 9 / 25 - Minibatch ==

Average Metric: 19.00 / 35 (54.3%): 100%|██████████| 35/35 [00:06<00:00,  5.74it/s]

2025/06/11 12:43:50 INFO dspy.evaluate.evaluate: Average Metric: 19 / 35 (54.3%)

🏃 View run eval_minibatch_6 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/defe4232717d455799aa459687d22353
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:43:50 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 54.29 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/06/11 12:43:50 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29]
2025/06/11 12:43:50 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0]
2025/06/11 12:43:50 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:43:50 INFO dspy.teleprompt.mipro_optimizer_v2: =========================================


2025/06/11 12:43:50 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 10 / 25 - Minibatch ==

Average Metric: 6.00 / 35 (17.1%): 100%|██████████| 35/35 [00:10<00:00,  3.31it/s]

2025/06/11 12:44:01 INFO dspy.evaluate.evaluate: Average Metric: 6 / 35 (17.1%)

2025/06/11 12:44:01 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 17.14 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/06/11 12:44:01 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14]
2025/06/11 12:44:01 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0]
2025/06/11 12:44:01 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:01 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:44:01 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 11 / 25 - Minibatch ==

🏃 View run eval_minibatch_7 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/52e4b7ecc87e46f2b844145ee217c7ae
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 13.00 / 35 (37.1%): 100%|██████████| 35/35 [00:06<00:00,  5.63it/s]

2025/06/11 12:44:07 INFO dspy.evaluate.evaluate: Average Metric: 13 / 35 (37.1%)

🏃 View run eval_minibatch_8 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/662a246f247046aea9539bbd9c3dc554
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:44:07 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 37.14 on minibatch of size 35 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/06/11 12:44:07 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14]
2025/06/11 12:44:07 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0]
2025/06/11 12:44:07 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:07 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:44:07 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 12 / 25 - Minibatch ==

Average Metric: 19.00 / 35 (54.3%): 100%|██████████| 35/35 [00:05<00:00,  6.13it/s]

2025/06/11 12:44:13 INFO dspy.evaluate.evaluate: Average Metric: 19 / 35 (54.3%)

2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 54.29 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29]
2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0]
2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 13 / 25 - Full Evaluation =====
2025/06/11 12:44:13 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 54.29) from minibatch trials...

🏃 View run eval_minibatch_9 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/26293a723e744d058d535741330fbd5a
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 49.00 / 100 (49.0%): 100%|██████████| 100/100 [00:24<00:00,  4.07it/s]

2025/06/11 12:44:38 INFO dspy.evaluate.evaluate: Average Metric: 49 / 100 (49.0%)
2025/06/11 12:44:38 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0]
2025/06/11 12:44:38 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:38 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2025/06/11 12:44:38 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/06/11 12:44:38 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 14 / 25 - Minibatch ==

🏃 View run eval_full_2 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/1f11e574817d423d99bca5c5cadf04cc
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 18.00 / 35 (51.4%): 100%|██████████| 35/35 [00:02<00:00, 14.32it/s]

2025/06/11 12:44:41 INFO dspy.evaluate.evaluate: Average Metric: 18 / 35 (51.4%)

2025/06/11 12:44:41 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 51.43 on minibatch of size 35 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/06/11 12:44:41 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43]
2025/06/11 12:44:41 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0]
2025/06/11 12:44:41 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:41 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:44:41 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 15 / 25 - Minibatch ==

🏃 View run eval_minibatch_10 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/003c1c5ae9b948c785c769acb8c87216
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 18.00 / 35 (51.4%): 100%|██████████| 35/35 [00:06<00:00,  5.37it/s]

2025/06/11 12:44:47 INFO dspy.evaluate.evaluate: Average Metric: 18 / 35 (51.4%)

🏃 View run eval_minibatch_11 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/f9f22e27bdea446e947ea75246dd9546
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:44:48 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 51.43 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 1'].
2025/06/11 12:44:48 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43]
2025/06/11 12:44:48 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0]
2025/06/11 12:44:48 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:48 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:44:48 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 16 / 25 - Minibatch ==

Average Metric: 19.00 / 35 (54.3%): 100%|██████████| 35/35 [00:06<00:00,  5.07it/s]

2025/06/11 12:44:55 INFO dspy.evaluate.evaluate: Average Metric: 19 / 35 (54.3%)
2025/06/11 12:44:55 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 54.29 on minibatch of size 35 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 4'].
2025/06/11 12:44:55 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29]
2025/06/11 12:44:55 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0]
2025/06/11 12:44:55 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:44:55 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:44:55 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 17 / 25 - Minibatch ==

🏃 View run eval_minibatch_12 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/3d123a5ae8e744069a1d28b5e823f883
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 17.00 / 35 (48.6%): 100%|██████████| 35/35 [00:05<00:00,  5.97it/s]

2025/06/11 12:45:01 INFO dspy.evaluate.evaluate: Average Metric: 17 / 35 (48.6%)

2025/06/11 12:45:01 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.57 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 5'].
2025/06/11 12:45:01 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57]
2025/06/11 12:45:01 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0]
2025/06/11 12:45:01 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:01 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:45:01 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 18 / 25 - Minibatch ==

🏃 View run eval_minibatch_13 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/ec719098ff7f4287a8d4c4ab7d7748aa
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 20.00 / 35 (57.1%): 100%|██████████| 35/35 [00:13<00:00,  2.62it/s]

2025/06/11 12:45:14 INFO dspy.evaluate.evaluate: Average Metric: 20 / 35 (57.1%)
2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 57.14 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57, 57.14]
2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0]
2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 19 / 25 - Full Evaluation =====
2025/06/11 12:45:14 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 57.14) from minibatch trials...

🏃 View run eval_minibatch_14 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/e8cb2c2c78ce40409c50f3011a1c2876
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 49.00 / 100 (49.0%): 100%|██████████| 100/100 [00:16<00:00,  6.25it/s]

2025/06/11 12:45:30 INFO dspy.evaluate.evaluate: Average Metric: 49 / 100 (49.0%)
2025/06/11 12:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0]
2025/06/11 12:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2025/06/11 12:45:31 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/06/11 12:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 20 / 25 - Minibatch ==

🏃 View run eval_full_3 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/9eb47ea25f2a4d909d9d38932196312a
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 17.00 / 35 (48.6%): 100%|██████████| 35/35 [00:06<00:00,  5.62it/s]

2025/06/11 12:45:37 INFO dspy.evaluate.evaluate: Average Metric: 17 / 35 (48.6%)

2025/06/11 12:45:37 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.57 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/06/11 12:45:37 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57, 57.14, 48.57]
2025/06/11 12:45:37 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0]
2025/06/11 12:45:37 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:37 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:45:37 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 21 / 25 - Minibatch ==

🏃 View run eval_minibatch_15 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/b205de3391a448ba900833d396c96885
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 21.00 / 35 (60.0%): 100%|██████████| 35/35 [00:06<00:00,  5.07it/s]

2025/06/11 12:45:44 INFO dspy.evaluate.evaluate: Average Metric: 21 / 35 (60.0%)

🏃 View run eval_minibatch_16 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/bf3aad5e01114c22838ff0db0fec8c72
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:45:44 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 3'].
2025/06/11 12:45:44 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57, 57.14, 48.57, 60.0]
2025/06/11 12:45:44 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0]
2025/06/11 12:45:44 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:44 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:45:44 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 22 / 25 - Minibatch ==

Average Metric: 18.00 / 35 (51.4%): 100%|██████████| 35/35 [00:05<00:00,  5.91it/s]

2025/06/11 12:45:50 INFO dspy.evaluate.evaluate: Average Metric: 18 / 35 (51.4%)
2025/06/11 12:45:50 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 51.43 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 5'].
2025/06/11 12:45:50 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57, 57.14, 48.57, 60.0, 51.43]
2025/06/11 12:45:50 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0]
2025/06/11 12:45:50 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:50 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:45:50 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 23 / 25 - Minibatch ==

🏃 View run eval_minibatch_17 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/61467dacdd544833b3821f4763662ab4
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 18.00 / 35 (51.4%): 100%|██████████| 35/35 [00:05<00:00,  5.89it/s]

2025/06/11 12:45:56 INFO dspy.evaluate.evaluate: Average Metric: 18 / 35 (51.4%)

🏃 View run eval_minibatch_18 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/d4e3234e999f4837bd2cca48ba29ad79
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

2025/06/11 12:45:57 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 51.43 on minibatch of size 35 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 3'].
2025/06/11 12:45:57 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57, 57.14, 48.57, 60.0, 51.43, 51.43]
2025/06/11 12:45:57 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0]
2025/06/11 12:45:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:45:57 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:45:57 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 24 / 25 - Minibatch ==

Average Metric: 17.00 / 35 (48.6%): 100%|██████████| 35/35 [00:10<00:00,  3.34it/s]

2025/06/11 12:46:07 INFO dspy.evaluate.evaluate: Average Metric: 17 / 35 (48.6%)
2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 48.57 on minibatch of size 35 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 3'].
2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: Minibatch scores so far: [8.57, 51.43, 14.29, 54.29, 48.57, 42.86, 54.29, 17.14, 37.14, 54.29, 51.43, 51.43, 54.29, 48.57, 57.14, 48.57, 60.0, 51.43, 51.43, 48.57]
2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0]
2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 50.0
2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: ==========================================


2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 25 / 25 - Full Evaluation =====
2025/06/11 12:46:07 INFO dspy.teleprompt.mipro_optimizer_v2: Doing full eval on next top averaging program (Avg Score: 60.0) from minibatch trials...

🏃 View run eval_minibatch_19 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/2e345ab195dd4e57b404acb825f26231
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Average Metric: 54.00 / 100 (54.0%): 100%|██████████| 100/100 [00:17<00:00,  5.69it/s]

2025/06/11 12:46:25 INFO dspy.evaluate.evaluate: Average Metric: 54 / 100 (54.0%)
2025/06/11 12:46:25 INFO dspy.teleprompt.mipro_optimizer_v2: New best full eval score! Score: 54.0
2025/06/11 12:46:25 INFO dspy.teleprompt.mipro_optimizer_v2: Full eval scores so far: [31.0, 50.0, 49.0, 49.0, 54.0]
2025/06/11 12:46:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far: 54.0
2025/06/11 12:46:25 INFO dspy.teleprompt.mipro_optimizer_v2: =======================
2025/06/11 12:46:25 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/06/11 12:46:25 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 54.0!

🏃 View run eval_full_4 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/9519c3d313ff4c4fa751bcf93642e3d9
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run gifted-pug-121 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/57871a627850406aa53dfee4bf7d523a
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245

[Trace(request_id=45a3b376cc554957b478f5ff591e67d0), Trace(request_id=266aecdfdde6465cbf9664610a2b256b), Trace(request_id=1ec711b14ba444b783387efc93890915), Trace(request_id=0d9c00cd851a4eb9a37a965fdd7704f2), Trace(request_id=70aacc1d5cb645e686a7b6009e40827b), Trace(request_id=384962842ca74e76abd9ab2cf0b6da58), Trace(request_id=5564171b75fd4103863b7f25d26c58f4), Trace(request_id=444566e9df1e4209983766a2a1320da6), Trace(request_id=7dc7ce699347488ab17f18dc7c375162), Trace(request_id=a1435d58f4364705b942f6403311f2f2)]

In [13]:
optimized_react.react.signature

StringSignature(question, trajectory -> next_thought, next_tool_name, next_tool_args
    instructions="Given the fields `question`, produce the fields `answer`.\n\nYou are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.\nYour goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.\n\nTo do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.\nAfter each tool call, you receive a resulting observation, which gets appended to your trajectory.\n\nWhen writing next_thought, you may reason about the current situation and plan for future steps.\nWhen selecting the next_tool_name and its next_tool_args, the tool must be one of:\n\n(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}} in JSON format.\n(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all infomration for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {} in JSON format."
    question = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Question:', 'desc': '${question}'})
    trajectory = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'input', 'prefix': 'Trajectory:', 'desc': '${trajectory}'})
    next_thought = Field(annotation=str required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Next Thought:', 'desc': '${next_thought}'})
    next_tool_name = Field(annotation=Literal['search_wikipedia', 'finish'] required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Next Tool Name:', 'desc': '${next_tool_name}'})
    next_tool_args = Field(annotation=dict[str, Any] required=True json_schema_extra={'__dspy_field_type': 'output', 'prefix': 'Next Tool Args:', 'desc': '${next_tool_args}'})
)

In [14]:
optimized_react.react.demos

[Example({'augmented': True, 'question': 'That Darn Cat! and Never a Dull Moment were both produced by what studio?', 'trajectory': '[[ ## thought_0 ## ]]\nI need to find out which studio produced both "That Darn Cat!" and "Never a Dull Moment." This information is likely available on Wikipedia, so I will search for it there.\n\n[[ ## tool_name_0 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_0 ## ]]\n{"query": "That Darn Cat! and Never a Dull Moment studio production"}\n\n[[ ## observation_0 ## ]]\n[1] «That Darn Cat! | That Darn Cat! is a 1965 American Walt Disney Productions thriller comedy film starring Hayley Mills (in her last of the six films she made for the Walt Disney Studios) and Dean Jones (starring in his first film for Disney) in a story about bank robbers, a kidnapping and a mischievous cat. The film was based on the 1963 novel "Undercover Cat" by Gordon and Mildred Gordon and was directed by Robert Stevenson. The title song was written by the Sherman Brothers and sung by Bobby Darin. The 1997 remake includes a cameo appearance by Dean Jones.»\n[2] «Never a Dull Moment (1968 film) | Never a Dull Moment is a 1968 American comedy crime film from Walt Disney Productions starring Dick Van Dyke and Edward G. Robinson and directed by Jerry Paris. The script by AJ Carothers was based on a novel by John Godey. The supporting cast features Dorothy Provine, Henry Silva, Slim Pickens and Jack Elam.»\n[3] «That Darn Cat (1997 film) | That Darn Cat is a 1997 American mystery comedy film starring Christina Ricci and Doug E. Doug. It is a remake of the 1965 film "That Darn Cat! ", which in turn was based on the book "Undercover Cat" by Gordon and Mildred Gordon. It is directed by British TV veteran Bob Spiers (most famous for "Fawlty Towers", as well as "Spice World") and written by Scott Alexander and Larry Karaszewski, best known for "Ed Wood" and the first two "Problem Child" films.»', 'next_thought': 'Both "That Darn Cat!" and "Never a Dull Moment" were produced by Walt Disney Productions. I have the information I need to answer the question.', 'next_tool_name': 'finish', 'next_tool_args': {}}) (input_keys=None),
 Example({'augmented': True, 'question': 'Which Centre did the author of "The Strange Death of Europe" found?', 'trajectory': '[[ ## thought_0 ## ]]\nI need to find out which Centre was founded by the author of "The Strange Death of Europe." This information might be available on Wikipedia, so I will search for it.\n\n[[ ## tool_name_0 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_0 ## ]]\n{"query": "author of \'The Strange Death of Europe\' founded Centre"}\n\n[[ ## observation_0 ## ]]\n[1] «The Strange Death of Europe | The Strange Death of Europe: Immigration, Identity, Islam is a 2017 book by the British journalist and political commentator, Douglas Murray. It was published in Britain in May 2017, and the U.S. edition in June, 2017.»\n[2] «The Strange Death of Liberal England | The Strange Death of Liberal England is a book written by George Dangerfield published in 1935. In it the author discusses the causes of the decline in the influence of the British Liberal Party in the years 1910 to 1914.»\n[3] «The Strange Death of Tory England | The Strange Death of Tory England is a book of political commentary by the journalist Geoffrey Wheatcroft, published in 2005.»\n\n[[ ## thought_1 ## ]]\nThe search did not provide information about the Centre founded by Douglas Murray, the author of "The Strange Death of Europe." I need to refine my search to focus specifically on Douglas Murray and any organizations or Centres he may have founded.\n\n[[ ## tool_name_1 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_1 ## ]]\n{"query": "Douglas Murray founded Centre"}\n\n[[ ## observation_1 ## ]]\n[1] «Douglas Murray (author) | Douglas Kear Murray (born 16 July 1979) is a British author, journalist, and political commentator. He is the founder of the Centre for Social Cohesion and is currently the associate director of the Henry Jackson Society and associate editor of "The Spectator".»\n[2] «Big Switch Networks | Big Switch Networks is a data center networking company. The company was founded by Kyle Forster and Guido Appenzeller in 2010 and has roots in the original Stanford research team that invented software defined networking (SDN). Douglas Murray, a former Juniper Networks and Sun Microsystems executive, joined the company as CEO in 2013 as the company went through a significant pivot following VMware\'s acquisition of Nicira.»\n[3] «Westgate, Oxford | The Westgate Shopping Centre (locally known as the Westgate Centre or Westgate) is a shopping centre in central Oxford, England, currently undergoing redevelopment. The original centre was built between 1970–72, designed by Douglas Murray and built by Taylor Woodrow. The centre was closed in February 2016 for comprehensive redevelopment, and is planned to re-open in October 2017.»', 'next_thought': 'I found that Douglas Murray is the founder of the Centre for Social Cohesion. This answers the question about which Centre he founded. I can now finish the task.', 'next_tool_name': 'finish', 'next_tool_args': {}}) (input_keys=None),
 Example({'augmented': True, 'question': 'Which publication has been published by a greater number of groups, House Beautiful or Smithsonian?', 'trajectory': '[[ ## thought_0 ## ]]\nI need to find out how many groups have published the magazine House Beautiful and how many have published Smithsonian. This information is likely available on Wikipedia, so I will search for both publications to compare their publication histories.\n\n[[ ## tool_name_0 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_0 ## ]]\n{"query": "House Beautiful magazine publication history"}\n\n[[ ## observation_0 ## ]]\n[1] «House Beautiful | House Beautiful is an interior decorating magazine that focuses on decorating and the domestic arts. First published in 1896, it is currently published by the Hearst Corporation, who began publishing it in 1934. It is the oldest still-published magazine in what is known as the "shelter magazine" genre.»\n[2] «Ethel B. Power | Ethel B. Power (1881–1969) was the editor of "House Beautiful" magazine in the 1920s and early 1930s, and in this capacity she championed a generation of women architects who emerged from the newly founded Cambridge School of Architecture and Landscape Architecture. A trained architect herself, she also published a compilation of plans for small houses by notable architects of the day.»\n[3] «Elizabeth Gordon (editor) | Elizabeth Gordon (August 8, 1906 - September 3, 2000) was editor of House Beautiful magazine from 1941 to 1964. She was remembered as "a missionary of taste to the American homemaker."»\n\n[[ ## thought_1 ## ]]\nI have found some information about House Beautiful, but I need to search for the publication history of Smithsonian to compare the number of groups that have published each magazine.\n\n[[ ## tool_name_1 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_1 ## ]]\n{"query": "Smithsonian magazine publication history"}\n\n[[ ## observation_1 ## ]]\n[1] «Smithsonian (magazine) | Smithsonian is the official journal published by the Smithsonian Institution in Washington, D.C. The first issue was published in 1970.»\n[2] «Air &amp; Space/Smithsonian | Air & Space/Smithsonian magazine is a bimonthly magazine put out by the National Air and Space Museum. Its first publishing was in April 1986. Because the museum is a part of the Smithsonian Institution, which puts out its own "Smithsonian" magazine, the magazine\'s full title is "Air & Space/Smithsonian". Therefore, the word "Smithsonian" appears on the cover, just beneath "AIR&SPACE", in a much smaller size.»\n[3] «Smithsonian Contributions and Studies Series | The Smithsonian Contributions and Studies Series is a collection of serial periodical publications produced by the Smithsonian Institution, detailing advances in various scientific and societal fields to which the Smithsonian Institution has made contributions.»\n\n[[ ## thought_2 ## ]]\nI have found that House Beautiful has been published since 1896 and is currently published by the Hearst Corporation. Smithsonian magazine, on the other hand, was first published in 1970 by the Smithsonian Institution. However, I still need to determine how many different groups have published each magazine over their histories. I will search for more detailed publication history for both magazines to find this information.\n\n[[ ## tool_name_2 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_2 ## ]]\n{"query": "House Beautiful magazine publishers history"}\n\n[[ ## observation_2 ## ]]\n[1] «House Beautiful | House Beautiful is an interior decorating magazine that focuses on decorating and the domestic arts. First published in 1896, it is currently published by the Hearst Corporation, who began publishing it in 1934. It is the oldest still-published magazine in what is known as the "shelter magazine" genre.»\n[2] «Ethel B. Power | Ethel B. Power (1881–1969) was the editor of "House Beautiful" magazine in the 1920s and early 1930s, and in this capacity she championed a generation of women architects who emerged from the newly founded Cambridge School of Architecture and Landscape Architecture. A trained architect herself, she also published a compilation of plans for small houses by notable architects of the day.»\n[3] «Elizabeth Gordon (editor) | Elizabeth Gordon (August 8, 1906 - September 3, 2000) was editor of House Beautiful magazine from 1941 to 1964. She was remembered as "a missionary of taste to the American homemaker."»', 'next_thought': 'I still need to find out how many different groups have published the Smithsonian magazine. The previous search did not provide enough information about the publishers of Smithsonian. I will search for the publication history of Smithsonian magazine to gather more details.', 'next_tool_name': 'search_wikipedia', 'next_tool_args': {'query': 'Smithsonian magazine publishers history'}}) (input_keys=None),
 Example({'augmented': True, 'question': 'What is the name of the school located near the Brea mall owned by Simon Property Group?', 'trajectory': '[[ ## thought_0 ## ]]\nI need to find the name of the school located near the Brea mall that is owned by Simon Property Group. This information might be available on Wikipedia or other reliable sources. I will search for it to gather the necessary details.\n\n[[ ## tool_name_0 ## ]]\nsearch_wikipedia\n\n[[ ## tool_args_0 ## ]]\n{"query": "school near Brea mall owned by Simon Property Group"}\n\n[[ ## observation_0 ## ]]\n[1] «Brea Mall | The Brea Mall is a shopping mall located in the Orange County city of Brea, California. Since 1998 the mall has been owned and operated by the Simon Property Group. It is home to four major department stores, over 175 specialty shops and boutiques, and a food court. It is approximately 1,310,000 square feet (1.31 million).»\n[2] «Briarwood Mall | Briarwood Mall is a shopping mall in Ann Arbor, Michigan, United States. The mall\'s four anchor stores are Macy\'s, JCPenney, Sears, and Von Maur. Surrounded by office and other development, the mall anchors the southern Ann Arbor commercial area around Eisenhower Boulevard and I-94. It serves as the primary shopping mall for all of Washtenaw County. Simon Property Group currently manages and co-owns the mall (Simon owns 50%). Briarwood is considered a Class A mall property by developers based on its sales per square foot. Many restaurants, hotels and stores surround the mall.»\n[3] «Mall at The Source | The Mall at the Source (also known as The Source Mall or simply The Source) is a shopping mall located in Westbury, New York, United States, on Old Country Road and Merchants Concourse (Ellison Avenue), currently managed by Newmark Grubb Knight Frank and owned by lenders. Until August 2012, the mall was managed and co-owned by Simon Property Group. Its last stores included an Old Navy, an H&M, and a David\'s Bridal. It currently only has a couple upscale restaurants — The Cheesecake Factory and P. F. Chang\'s China Bistro — a Dave & Buster\'s, a Lord and Taylor outlet, a Fortunoff\'s outdoor furniture outlet, a Gymboree Play & Music, a few discount retailers, an rescue animal shelter, and small standalone kiosks. The mall was named for its former anchor store Fortunoff (which used the phrase "The Source" in advertising for the chain), which the mall was built around and which closed in June 2009.»', 'next_thought': 'The search did not return any information about the school near the Brea mall owned by Simon Property Group. I need to refine my search or look for other sources that might provide this specific information.', 'next_tool_name': 'search_wikipedia', 'next_tool_args': {'query': 'Brea mall school Simon Property Group'}}) (input_keys=None)]

In [15]:
evaluator = dspy.Evaluate(
    metric=dspy.evaluate.answer_exact_match,
    devset=valset,
    display_table=True,
    display_progress=True,
    num_threads=24,
)

In [16]:
original_score = evaluator(react)
print(f"Original score: {original_score}")

Average Metric: 31.00 / 100 (31.0%): 100%|██████████| 100/100 [00:04<00:00, 23.21it/s]

2025/06/11 12:47:02 INFO dspy.evaluate.evaluate: Average Metric: 31 / 100 (31.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to find out which movie ""the king of cool"" s...","Steve McQueen, known as ""the king of cool,"" starred in the movie ""...","The movie is ""The Great Escape.""",
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': 'I need to determine which individual, Robert Kardas...",Robert Kardashian's family is well-known for their reality TV show...,Robert Kardashian's family had their own reality TV show.,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,"{'thought_0': 'I need to find out which star in the film ""Shadows ...","I searched for information about the cast of the 1986 film ""Shadow...",There is no information available about a Russian ballerina in the...,
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,"{'thought_0': ""I need to find out who appointed Amashsai and the m...",Nehemiah appointed Amashsai to work at the temple in Jerusalem. Th...,"The meaning of the name of the man who appointed Amashsai, Nehemia...",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'I need to find out what additional requirements or ...,To gain access to 173 countries and territories with an Austrian p...,"In addition to the Austrian passport, travelers may need to obtain...",
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'I need to find out the name of the American actress...,The American actress and singer-songwriter known for her role as P...,2007,
96,What animated creatures were the title characters of the film whic...,seals,{'thought_0': 'I need to identify the animated creatures that were...,The animated creatures that are the title characters of the film b...,The animated creatures that are the title characters of the film b...,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to find out which private, coeducational col...",The 1925 Saint Mary's Gaels football team represented Saint Mary's...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'I need to verify the nationalities and contribution...,Both Dorothy Arzner and Richard Wallace were confirmed to be Ameri...,"No, neither Dorothy Arzner nor Richard Wallace were French film di...",
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'I need to find out the recording or performing star...,Moya Brennan began performing professionally in 1970 with her fami...,Moya Brennan started recording/performing earlier than David Donato.,

🏃 View run learned-mole-374 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/822e315fa68d46bba73d5ace91c7d750
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Original score: 31.0

[Trace(request_id=3aa5d722512f44c897d1cd5482e845a9), Trace(request_id=ca054fe88402403f8d7d5d606567c62d), Trace(request_id=b2aab57f95ae40b38eb5cb58cad25fbc), Trace(request_id=5b5d2b4b814e4cec96f798d593f0adaa), Trace(request_id=48720080ea614d7389225cac8d01675a), Trace(request_id=72d9f0948101409ebcbda6b52cd22aac), Trace(request_id=98d5ab07ea174b11bd58219fa4e23b32), Trace(request_id=49bc3d90a40d4b3299d63fe26898d079), Trace(request_id=59270707506d4c50b932afcae8a116b0), Trace(request_id=4073734e120c4c399e479b9267e80bb4)]

In [17]:
optimized_score = evaluator(optimized_react)
print(f"Optimized score: {optimized_score}")

Average Metric: 54.00 / 100 (54.0%): 100%|██████████| 100/100 [00:04<00:00, 22.36it/s]

2025/06/11 12:47:10 INFO dspy.evaluate.evaluate: Average Metric: 54 / 100 (54.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to find out which movie ""the king of cool"" s...",I found that Bud Ekins was Steve McQueen's stunt double in the fil...,The Great Escape,✔️ [True]
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,{'thought_0': 'I need to find out which family had their own reali...,"The Kardashian family, associated with Robert Kardashian, has thei...",Robert Kardashian,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,"{'thought_0': 'I need to find out which star in ""Shadows in Paradi...","In my search for the cast of ""Shadows in Paradise,"" I found that t...",Sofya Skya,✔️ [True]
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,"{'thought_0': ""I need to find out who appointed Amashsai and the m...","Amashsai was appointed by Nehemiah, and the name Amasai, which is ...","""Burdensome""",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'I need to find out what additional requirements are...,The search results indicate that Austrian citizens have visa-free ...,"A valid Austrian passport, and potentially a visa or health docume...",
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'I need to find out the release date of the first al...,I found that the American actress and singer-songwriter Katey Saga...,"April 19, 1994",✔️ [True]
96,What animated creatures were the title characters of the film whic...,seals,{'thought_0': 'I need to identify the animated creatures that were...,The question pertains to animated creatures that are the title cha...,"Fairies (specifically Puck, Titania, and Oberon)",
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to find out which private, coeducational col...",The 1925 Saint Mary's Gaels football team represented Saint Mary's...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,"{'thought_0': ""I need to determine if both Dorothy Arzner and Rich...","I found that Dorothy Arzner was an American film director, and Ric...","No, neither Dorothy Arzner nor Richard Wallace were French film di...",
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'I need to find out the recording or performing hist...,Moya Brennan began performing professionally in 1970 with the band...,Moya Brennan,✔️ [True]

🏃 View run vaunted-jay-653 at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245/runs/b5d483f7878649e880ed7d4458aace44
🧪 View experiment at: https://s172-29-44-69p8080.lab-aws-production.deeplearning.ai/#/experiments/272351694886347245
Optimized score: 54.0

[Trace(request_id=ee44765055d74a57b6b38208dc5d54ab), Trace(request_id=fa1e98c94ced44d2aa24862717570c75), Trace(request_id=781cf44d0a164b11bc3d307bb6601091), Trace(request_id=35f9d3a4ba784a2fb5162e63782fac6b), Trace(request_id=ba328bbc375e4a9a8ad53c3dbaa9b948), Trace(request_id=815c48d35ed0471ba975931d1a945953), Trace(request_id=cf5b0c86fe0e421a805429f08ae76eec), Trace(request_id=9da7b350bf174290baf67db4d24b8c6e), Trace(request_id=0a4c447e9a3144e68b67919617bd34db), Trace(request_id=c4d88e86045b4f8abfca590cffb41d98)]